[package]
name = "lee"
version = "0.0.1"
authors = ["zetok"]



[dependencies.rstox]
git = "https://github.com/suhr/rstox.git"


[dependencies.markov]
markov = "*"

[dependencies.chrono]
chrono = "0.2"

[dependencies.rand]
rand = "0.3"
