[package]

name = "dice_bot"
version = "0.0.1"
authors = ["subliun <subliunisdev@gmail.com>"]

[dependencies.tox]

git = "https://github.com/subliun/rust-tox.git"

[dependencies.markov]

git = "https://github.com/aatxe/markov.git"
