[package]
name = "lee"
version = "0.0.5"
authors = ["zetok"]



[dependencies.rstox]
git = "https://github.com/suhr/rstox.git"


[dependencies.markov]
markov = "0.0.29"

[dependencies.chrono]
chrono = "0.2"

[dependencies.rand]
rand = "0.3"
