[package]
name = "lee"
version = "0.0.0"
authors = ["zetok"]



[dependencies.rstox]

git = "https://github.com/suhr/rstox.git"
branch="new-api"


[dependencies.markov]
markov = "*"

[dependencies.chrono]
chrono = "0.2"

[dependencies.rand]
rand = "0.3"
